controller_list:
  - name: fake_leftShoulderPalm_controller
    joints:
      - leftShoulderPitch
      - leftShoulderRoll
      - leftShoulderYaw
      - leftElbowPitch
      - leftForearmYaw
      - leftWristRoll
      - leftWristPitch
  - name: fake_rightShoulderPalm_controller
    joints:
      - rightShoulderPitch
      - rightShoulderRoll
      - rightShoulderYaw
      - rightElbowPitch
      - rightForearmYaw
      - rightWristRoll
      - rightWristPitch
  - name: fake_rightTorsoPalm_controller
    joints:
      - torsoYaw
      - torsoPitch
      - torsoRoll
      - rightShoulderPitch
      - rightShoulderRoll
      - rightShoulderYaw
      - rightElbowPitch
      - rightForearmYaw
      - rightWristRoll
      - rightWristPitch
  - name: fake_leftTorsoPalm_controller
    joints:
      - torsoYaw
      - torsoPitch
      - torsoRoll
      - leftShoulderPitch
      - leftShoulderRoll
      - leftShoulderYaw
      - leftElbowPitch
      - leftForearmYaw
      - leftWristRoll
      - leftWristPitch