robot_name: Valkyrie

world_frame_id: /world

### upper body settings ########################################################
upper_body:
  size: {x: 0.4, y: 0.84, z: 1.66} # [m]
  origin_shift: {x: 0.00, y: 0.00, z: 0.00} # [m], transformation from center to shifted frame

### foot settings ##############################################################
foot:
  size: {x: 0.27, y: 0.18, z: 0.015} # [m]
  separation: 0.25 # [m]
  origin_shift: {x: 0.02, y: 0.0}
  left: # position of planner foot frame (center of sole) given in robot's "foot" tf frame
    frame_id: /l_leg_foot_link
    foot_frame:
      {x:  0.00, y:  0.18, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00}  # 3x[m] 3x[rad]
  right: # position of planner foot frame (center of sole) given in robot's "foot" tf frame
    frame_id: /r_leg_foot_link
    foot_frame:
      {x:  0.00, y: -0.18, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00}  # 3x[m] 3x[rad]

### pelvis pose to feet center (on ground) transform ###########################
pelvis_to_feet_center: {x: 0.0, y: 0.0, z: -0.896} # [m]
